### ISSUE TITLE
Why does minimum dependency require iOS 14.0

### ISSUE THREAD

**Issue by kaaaaai** [nayanAubie/msal_auth#20]
As the question, according to the official version the minimum dependency is 13.0, can you support it?

**Comment by kaaaaai** [comment]
It is also not possible to obtain the idtoken ....

**Comment by nayanAubie** [comment]
@kaaaaai I'll look for version 13, but obtaining `idToken` is a different thing and you can provide the code snippet so I can look more into it.

**Comment by nayanAubie** [comment]
The deployment target in the [MSAL iOS](https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL.podspec) library is `14.0`

**Comment by politebarista** [comment]
@kaaaaai have you managed to get `idToken` somehow?

**Comment by nayanAubie** [comment]
@politebarista `idToken` is there, you can check `AuthenticationResult` class after calling `acquireToken` / `acquireTokenSilent`

**Comment by politebarista** [comment]
@nayanAubie Yes, you are right, the parameter does exist, only in my case it does not have a value on Android, but on iOS it consistently comes. 
I think we should continue the conversation in the https://github.com/nayanAubie/msal_auth/issues/27 or create a new issue, because, again in my case, the absence of `authority` during the `acquireTokenSilent` is caused by the `idToken` coming null during `acquireToken`
